apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T16:32:25Z"
  labels:
    operated-alertmanager: "true"
  name: alertmanager-operated
  namespace: prometheus
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Alertmanager
    name: prometheus-prometheus-oper-alertmanager
    uid: e281a9dd-0d76-46fe-ac63-f9034547e0d3
  resourceVersion: "10598"
  selfLink: /api/v1/namespaces/prometheus/services/alertmanager-operated
  uid: 87249933-c00e-43a1-8eca-ad37003bc8a2
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: tcp-mesh
    port: 9094
    protocol: TCP
    targetPort: 9094
  - name: udp-mesh
    port: 9094
    protocol: UDP
    targetPort: 9094
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
