apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T16:32:13Z"
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-operator
    helm.sh/chart: prometheus-operator-0.13.4
  name: prometheus-prometheus-oper-prometheus
  namespace: prometheus
  resourceVersion: "11351"
  selfLink: /api/v1/namespaces/prometheus/services/prometheus-prometheus-oper-prometheus
  uid: 28f49c1f-9333-476c-8329-347b5acd19de
spec:
  clusterIP: 10.96.130.46
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30134
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: prometheus-prometheus-oper-prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
