apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T16:32:13Z"
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-operator
    helm.sh/chart: prometheus-operator-0.13.4
  name: prometheus-prometheus-oper-alertmanager
  namespace: prometheus
  resourceVersion: "12118"
  selfLink: /api/v1/namespaces/prometheus/services/prometheus-prometheus-oper-alertmanager
  uid: d6607c6e-55df-4961-9595-861dafb6325e
spec:
  clusterIP: 10.111.169.33
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30325
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: prometheus-prometheus-oper-alertmanager
    app: alertmanager
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
