apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-03-12T16:32:13Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: 0.18.1
    helm.sh/chart: node-exporter-0.2.6
    jobLabel: node-exporter
  name: prometheus-node-exporter
  namespace: prometheus
  resourceVersion: "10511"
  selfLink: /api/v1/namespaces/prometheus/services/prometheus-node-exporter
  uid: e7973a2c-ebf2-46d5-b184-888586e04384
spec:
  clusterIP: 10.96.189.0
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: node-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
