apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T16:32:13Z"
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-operator
    helm.sh/chart: prometheus-operator-0.13.4
  name: prometheus-prometheus-oper-operator
  namespace: prometheus
  resourceVersion: "10505"
  selfLink: /api/v1/namespaces/prometheus/services/prometheus-prometheus-oper-operator
  uid: a99526ac-9dd7-4ced-87c8-47693ba20666
spec:
  clusterIP: 10.108.189.221
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
