apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T16:45:58Z"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-1.2.12
  name: grafana
  namespace: prometheus
  resourceVersion: "12460"
  selfLink: /api/v1/namespaces/prometheus/services/grafana
  uid: 4157e6d9-bd71-4e1b-a1cf-e8b40b0fa23e
spec:
  clusterIP: 10.109.134.188
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30317
    port: 3000
    protocol: TCP
    targetPort: dashboard
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
